os: linux
language: android
android:
  components:
    - build-tools-29.0.2
    - android-30
node_js:
- '12'
branches:
  only:
  - main
cache:
  directories:
  - node_modules
before_install: 
  - yes | sdkmanager "platforms;android-30"
  - yes | sdkmanager "build-tools;29.0.2"
  - nvm install 12
  - npm update
  - chmod +x ./android/gradlew
install:
- npm install
script:
- npm test
- "./android/gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug -p android/"
