os: linux
language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-29.0.2
    - android-30
before_install:
  - yes | sdkmanager "platforms;android-30"
  - yes | sdkmanager "build-tools;29.0.2"
  - nvm install && nvm use
  - npm install -g "npm@$(jq -r '.engines.npm' package.json)"
install:
  - npm ci
script:
  - "./android/gradlew assembleRelease -p android/"